openmobilemaps/maps-core

- .github/workflows/android.yml
- .github/workflows/ios.yml
- Package.resolved
- Package.swift
SPM does not allow un-version requirements in a version-based dependency.
> Specify djinni version in Package.swift

- shared/src/map/layers/objects/Textured2dLayerObject.cpp
- shared/src/map/layers/objects/Textured2dLayerObject.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.h
- adds alpha animation when adding a new tile to Tiled2dMapRasterLayer
> Alpha animation of Textured2dLayerObject

- android/src/main/java/io/openmobilemaps/mapscore/shared/graphics/GlTextureView.kt
- android/src/main/java/io/openmobilemaps/mapscore/shared/map/scheduling/AndroidScheduler.kt
- android/src/main/java/io/openmobilemaps/mapscore/shared/map/view/MapView.kt
- shared/src/map/MapScene.cpp
- shared/src/map/MapScene.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Fixed invalidate lag, slimmed down graphics task in onTilesUpdated of RasterLayer
> Android Invalidate Lag

- ios/graphics/Texture/TextureHolder.swift
- ios/maps/MCMapView.swift
- ios/maps/MCTextureLoader.swift
- disable rendering if app is in background
> iOS rendering improvements

- shared/src/map/layers/tiled/Tiled2dMapSource.h
- shared/src/map/layers/tiled/Tiled2dMapSourceImpl.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterSource.cpp
- fixes duplicate tile loading
- update priority of tiles that are already in the queue
> Fixes duplicate tile loading

- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
- zoom inertia is still missing
- rotation inertia is missing as well
> Implements simple dragging inertia

- CHANGELOG.md
- android/build.gradle
- android/readme.md
- ios/readme.md
- shared/src/MapsCoreSharedModule.cpp
- adds wmts parsing readme
- adds polygon layer readme
- adds icon layer readme
> Update plattform readme

- .github/workflows/sonatype-develop.yml
- android/build.gradle
- android/gradle.properties
Use explicit version code for prefab configuration instead of VERSION_NAME.
> Prefab Configuration Version

- ios/maps/MCMapView.swift
- ios/maps/MCMapViewTouchHandler.swift
- ios/maps/Scheduling/CLLocation+MapCore.swift
- ios/maps/Scheduling/MCScheduler.swift
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/controls/DefaultTouchHandler.cpp
- shared/src/map/layers/tiled/Tiled2dMapSource.h
- shared/src/map/layers/tiled/Tiled2dMapSourceImpl.h
- fixes several retain cycles (resolves issue #56)
- disabled touch handler logging
- fixes issues in camera after position was set
> Several fixes

- android/gradle.properties
- android/readme.md
- ios/maps/MCMapView.swift
- ios/maps/MCMapViewTouchHandler.swift
- ios/maps/Scheduling/CLLocation+MapCore.swift
- ios/maps/Scheduling/MCScheduler.swift
- shared/src/MapsCoreSharedModule.cpp
- shared/src/map/MapScene.cpp
- shared/src/map/MapScene.h
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/controls/DefaultTouchHandler.cpp
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/tiled/Tiled2dMapSource.h
- shared/src/map/layers/tiled/Tiled2dMapSourceImpl.h
> Release 1.3.1

- CHANGELOG.md
- android/gradle.properties
- android/readme.md
- shared/src/MapsCoreSharedModule.cpp
Prepare changelog/readme and version codes for release 1.3.2
> Prepare Release 1.3.2

- .github/workflows/sonatype.yml
- CHANGELOG.md
Adjusted the android release action to only execute on main tags, updated changelog
> Android Release Action and Changelog Update

- android/src/main/java/io/openmobilemaps/mapscore/graphics/GlTextureView.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/loader/TextureLoader.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
Fixed a memory leak in the MapView for Android.
> Memory Leak MapView.kt

- android/readme.md
- android/src/main/java/io/openmobilemaps/mapscore/MapsCore.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
Add a static initializer for loading the Android mapscore library
> Android Initializer

- shared/src/MapsCoreSharedModule.cpp
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/line/LineLayer.h
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.h
Fixed handling of async graphics tasks in TiledRaster-, Line- and PolygonLayer
> Async Setup Fix

- CHANGELOG.md
- android/gradle.properties
- android/readme.md
Adjusted changelog, readme and version numbers for release 1-3-3
> Prepare Release 1.3.3

- shared/src/map/MapScene.cpp
- shared/src/map/MapScene.h
Layers can now be inserted at arbitrary positions
> Layer Indexing

- ios/graphics/Common/MetalContext.swift
- ios/graphics/Helpers/MCRectD+Float.swift
- ios/graphics/Helpers/MCVec2D+Float.swift
- ios/graphics/Helpers/UIColor+Metal.swift
- ios/graphics/Model/BaseGraphicsObject.swift
- ios/graphics/Model/Line/Line2d.swift
- ios/graphics/Model/Line/LineGroup2d.swift
- ios/graphics/Model/Line/LineVertex.swift
- ios/graphics/Model/Polygon/Polygon2d.swift
- ios/graphics/Model/Polygon/PolygonGroup2d.swift
- ios/graphics/Model/Quad2d.swift
- ios/graphics/Model/Text/Text.swift
- ios/graphics/Pipelines/PipelineLibrary.swift
- ios/graphics/RenderingContext.swift
- ios/graphics/Samplers/SamplerLibrary.swift
- ios/graphics/Shader/AlphaShader.swift
- ios/graphics/Shader/BaseShader.swift
- ios/graphics/Shader/ClearStencilShader.swift
- ios/graphics/Shader/ColorCircleShader.swift
- ios/graphics/Shader/ColorLineShader.swift
- ios/graphics/Shader/ColorShader.swift
- ios/graphics/Shader/LineGroupShader.swift
- ios/graphics/Shader/PolygonGroupShader.swift
- ios/graphics/Shader/TextShader.swift
- ios/graphics/StaticMetalLibrary.swift
- shared/public/Tiled2dMapSource.h
- this enables users of maps-core to provide their own shaders
> iOS custom shaders

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
- bridging/android/jni/map/NativeMapCamera2dInterface.cpp
- bridging/ios/MCMapCamera2dInterface+Private.mm
- bridging/ios/MCMapCamera2dInterface.h
- djinni/map/core.djinni
- shared/public/MapCamera2dInterface.h
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Correct padding behavior for Map2dCamera.
> Padding Fixes

- android/src/main/java/io/openmobilemaps/mapscore/graphics/GlTextureView.kt
- bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
- bridging/android/jni/map/NativeMapCamera2dInterface.cpp
- bridging/ios/MCMapCamera2dInterface+Private.mm
- bridging/ios/MCMapCamera2dInterface.h
- djinni/map/core.djinni
- shared/public/MapCamera2dInterface.h
- shared/public/Vec2FHelper.h
- shared/src/graphics/helpers/Vec2FHelper.cpp
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Added method in Camera2d to zoom to bounding box. Fixed an unnecessary OpenGl error log.
> Move to Bounding Box

- shared/public/Vec2DHelper.h
- shared/src/graphics/helpers/Vec2DHelper.cpp
- shared/src/map/camera/MapCamera2d.cpp
Fixed the camera padding for moveTo and getCenter. Also added proper support for rotation.
> Camera2d Padding

- android/src/main/java/io/openmobilemaps/mapscore/map/scheduling/AndroidScheduler.kt
Allow setting the coroutine dispatchers in the android scheduler.
> Configurable Android Scheduler

- shared/src/graphics/Renderer.cpp
- shared/src/graphics/Renderer.h
- use priority_queue to sort renderpasses by renderPassIndex
> RenderPassIndex ordering of render items

- android/build.gradle
Enabling native debug symbols for Android.
> Android Debug Symbols

- shared/src/graphics/Renderer.cpp
- shared/src/graphics/Renderer.h
Keep insertion order within render pass render order.
> Keep insertion order within render pass render order

- shared/src/map/camera/MapCamera2d.cpp
Fixed setting rotation in MapCamera2d with padding, return correctly adjusted center position in getCenterPosition
> SetRotation with Padding, Fix getCenterPosition

- shared/src/map/coordinates/CoordinateSystemFactory.cpp
Increase bounds of epsg 2056 and 21781 to include the whole area of Switzerland
> EPSG 2056/21781 Bounds

- android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/line/LineLayer.h
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.h
- shared/src/map/layers/text/TextLayer.cpp
- shared/src/map/layers/text/TextLayer.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.h
Add locking to precomputed renderPass collections in layers.
> RenderPass locking

- ios/graphics/Shader/Metal/BaseShader.metal
- ios/graphics/Shader/Metal/LineShader.metal
- ios/graphics/Shader/Metal/PolygonGroupShader.metal
this fixes issues with stencil buffers/masking
> Bugfix: discard transparent pixels

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/polygon/PolygonLayerInterface.kt
- bridging/android/jni/map/layers/polygon/NativePolygonLayerInterface.cpp
- bridging/ios/MCPolygonLayerInterface+Private.mm
- bridging/ios/MCPolygonLayerInterface.h
- djinni/map/layers/polygon/polygon.djinni
- shared/public/PolygonLayerInterface.h
- shared/src/map/layers/polygon/PolygonCompare.h
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.h
Signed-off-by: Marco Zimmermann <zimmermann@ubique.ch>
> Adds possibility to add multiple polygons per identifier

- android/readme.md
Fixed code sample for wmts resources in the Android readme.
> Android Readme WMTS Sample Fix

- android/src/main/cpp/graphics/objects/Line2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Polygon2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.h
- android/src/main/cpp/graphics/objects/Text2dOpenGl.cpp
- android/src/main/cpp/graphics/shader/AlphaShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorCircleShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/TextShaderOpenGl.cpp
Fixed glError for untextured QuadOpenGl, removed checkOpenGl calls
> GLError Untextured Quad

- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
Fixes the rendering of the  ColorLineGroup2dShaderOpenGl.
> LineGroup2dOpenGl Fix

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
- bridging/android/jni/map/NativeMapCamera2dInterface.cpp
- bridging/ios/MCMapCamera2dInterface+Private.mm
- bridging/ios/MCMapCamera2dInterface.h
- djinni/map/core.djinni
- shared/public/MapCamera2dInterface.h
- shared/src/graphics/RenderObject.cpp
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Signed-off-by: Marco Zimmermann <zimmermann@ubique.ch>
> adds function to get padding adjusted visible rect

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/line/LineLayerInterface.kt
- bridging/android/jni/map/layers/line/NativeLineLayerInterface.cpp
- bridging/ios/MCLineLayerInterface+Private.mm
- bridging/ios/MCLineLayerInterface.h
- djinni/map/layers/line/line.djinni
- shared/public/LineLayerInterface.h
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/line/LineLayer.h
Support selection in LineLayer
> LineLayer Selection

- ios/graphics/Shader/Metal/LineShader.metal
Signed-off-by: Marco Zimmermann <zimmermann@ubique.ch>
> Fixes linegroup alpha shading

- android/src/main/cpp/graphics/OpenGlContext.cpp
- android/src/main/cpp/graphics/OpenGlContext.h
- android/src/main/cpp/graphics/OpenGlHelper.h
- android/src/main/cpp/graphics/objects/Polygon2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Polygon2dOpenGl.h
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.h
Improved rendering performance for OpenGL
> Performance OpenGL

- shared/src/map/camera/MapCamera2d.cpp
Fix moving to boundingBox in a different coordinate system than the map system.
> System Bugfix in MoveToBoundingBox

- shared/public/LineLayer.h
- shared/public/ShaderFactoryInterface.h
- shared/src/map/MapScene.cpp
- shared/src/map/MapScene.h
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/icon/IconLayer.h
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/tiled/Tiled2dMapLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Ensure a higher tolerance for inconveniently destroyed MapScenes
> Layer Destruction

- shared/src/map/MapScene.cpp
Do not remove/readd a layer when inserted in the same position again.
> Insert Layer at twice

- shared/public/ShaderFactoryInterface.h
Removed obsolete logging statement.
> Obosolete Log

- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Split rotation and zoom animation.
> Split Camera Animations

- android/src/main/java/io/openmobilemaps/mapscore/map/loader/DataLoader.kt
Expose okHttp client for subclasses in Android DataLoader
> Android DataLoader Client

- shared/src/map/layers/tiled/Tiled2dMapLayer.cpp
Clear mapInterface onRemove in Tiled2dMapLayer.
> Tiled2dMapLayer OnRemove

- shared/public/Tiled2dMapSourceImpl.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Reduce scope of multiple locks in the Tiled2dMap(Raster)Layer.
> Tiled2dMapLayer Locking

- android/src/main/cpp/graphics/objects/Line2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Line2dOpenGl.h
- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.h
- android/src/main/cpp/graphics/objects/Polygon2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Polygon2dOpenGl.h
- android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.h
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.h
- android/src/main/cpp/graphics/objects/Text2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Text2dOpenGl.h
Ensure proper data setting/readying in OpenGl graphics objects
> OpenGL GraphicsObjects Locking

- shared/public/Tiled2dMapSourceImpl.h
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/icon/IconLayer.h
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/text/TextLayer.cpp
- shared/src/map/layers/text/TextLayer.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Ensure unlocked in Tiled2dMapSource when notifying listeners.
> Tiled2dMapSource Locking

- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Clean up listeners in MapCamera2d, notify listeners on rotation animation
> MapCamera2D Rotation Update

- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
Provide an interface to store the next rendered frame
> Android: Save Frame 

- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
- bridging/android/java/io/openmobilemaps/mapscore/shared/map/controls/TouchAction.kt
- bridging/ios/MCTouchAction.h
- djinni/map/controls/touch_handler.djinni
- ios/maps/MCMapViewTouchHandler.swift
- shared/public/TouchAction.h
- shared/src/map/controls/DefaultTouchHandler.cpp
- shared/src/map/controls/DefaultTouchHandler.h
> handle Android's touch cancel event to avoid leaking touch interaction

- ios/maps/MCMapView.swift
- shared/public/CoordinatesUtil.h
- adds checkRectContainsCoord to coordutil
- reduce framesToRenderAfterInvalidate on iOS
> adds checkRectContainsCoord to coordutil

- Package.swift
- defines ndebug in package.swift https://github.com/apple/swift-package-manager/issues/4504
> defines NDEBUG in release builds

- android/src/main/cpp/graphics/shader/BaseShaderProgramOpenGl.h
- android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.h
Split uniform arrays in the OpenGL line group shader.
> Uniform Split OpenGL

- android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
- android/src/main/java/io/openmobilemaps/mapscore/graphics/GlTextureView.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/MapViewInterface.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/MapViewRenderHelper.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/MapViewRenderState.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/OffscreenMapRenderer.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/SaveFrameCallback.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/SaveFrameSpec.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/util/SaveFrameUtil.kt
- bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
- bridging/android/jni/map/NativeMapCamera2dInterface.cpp
- bridging/ios/MCMapCamera2dInterface+Private.mm
- bridging/ios/MCMapCamera2dInterface.h
- djinni/map/core.djinni
- shared/public/MapCamera2dInterface.h
- shared/public/Tiled2dMapSource.h
- shared/public/Tiled2dMapSourceImpl.h
- shared/src/map/MapScene.cpp
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
Added an OffscreenMapRenderer for Android, restructured Android OpenGL rendering, added a function to freeze the MapCamera2d and added a check for pending view bounds updates in the Tiled2dMapSource
> Android Offscreen Rendering

- shared/src/graphics/Renderer.cpp
- shared/src/graphics/Renderer.h
- shared/src/map/camera/MapCamera2d.cpp
- shared/src/map/camera/MapCamera2d.h
> faster calculation by moving out of creation of matrices

- android/src/main/java/io/openmobilemaps/mapscore/graphics/GlTextureView.kt
Keep pending tasks/target framerate when GLThread is not yet available.
> Pending GL Tasks

- shared/src/map/camera/MapCamera2d.cpp
fixes a bug in inertia where in t2 the map would always move to the top right
> Inertia Bugfix

- ios/graphics/Model/BaseGraphicsObject.swift
- ios/graphics/Model/Quad2d.swift
otherwise objects without textures are never rendered
> Bugfix iOS: set ready to true on setup 

- ios/maps/MCMapView.swift
fixes iOS deadlock when MCMapView.renderToImage is called from the main queue
> Bugfix: iOS deadlock

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.kt
- bridging/android/jni/map/layers/tiled/vector/NativeTiled2dMapVectorLayerInterface.cpp
- bridging/ios/MCTiled2dMapVectorLayerInterface+Private.mm
- bridging/ios/MCTiled2dMapVectorLayerInterface.h
- djinni/map/layers/tiled/vector/tiled_vector_layer.djinni
- shared/public/Tiled2dMapVectorLayer.h
- shared/public/Tiled2dMapVectorLayerInterface.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.cpp
- shared/src/map/layers/tiled/vector/parsing/Tiled2dMapVectorLayerParserHelper.h
Add custom layerName argument to Tiled2dMapVectorLayer
> Vector Layer Name

- shared/src/map/camera/MapCamera2d.cpp
Fix missing onTouchDown return.
> Missing Return onTouchDown

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.kt
- bridging/android/jni/map/layers/tiled/vector/NativeTiled2dMapVectorLayerInterface.cpp
- bridging/ios/MCTiled2dMapVectorLayerInterface+Private.mm
- bridging/ios/MCTiled2dMapVectorLayerInterface.h
- djinni/map/layers/tiled/vector/tiled_vector_layer.djinni
- ios/graphics/Shader/Metal/TextShader.metal
- ios/graphics/Shader/TextShader.swift
- shared/public/BackgroundVectorLayerDescription.h
- shared/public/LineVectorLayerDescription.h
- shared/public/OBB2D.h
- shared/public/PolygonVectorLayerDescription.h
- shared/public/RasterVectorLayerDescription.h
- shared/public/SymbolVectorLayerDescription.h
- shared/public/Tiled2dMapVectorLayer.h
- shared/public/Tiled2dMapVectorLayerConfig.h
- shared/public/Tiled2dMapVectorLayerInterface.h
- shared/public/Tiled2dMapVectorSource.h
- shared/public/Tiled2dMapVectorTileInfo.h
- shared/public/VectorLayerDescription.h
- shared/public/VectorMapDescription.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.cpp
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorSource.cpp
- shared/src/map/layers/tiled/vector/parsing/Tiled2dMapVectorLayerParserHelper.h
- shared/src/map/layers/tiled/vector/sublayers/symbol/Tiled2dMapVectorSymbolSubLayer.cpp
- shared/src/map/layers/tiled/vector/sublayers/symbol/Tiled2dMapVectorSymbolSubLayer.h
- adds support for multiple vector sources in a style.json
- fixes some bugs in symbol collision detection
> multi vector source

- shared/public/UnitBezier.h
> Fix includes for UnitBezier

- shared/src/map/layers/tiled/vector/Tiled2dMapVectorSource.cpp
Decode all features, when not asked for specific vector sublayers.
> No Layers to Decode

- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/TextShaderOpenGl.cpp
- android/src/main/java/io/openmobilemaps/mapscore/graphics/GLThread.kt
Trade-off fix for Quad2dOpenGl 1285 issues, remove checkGlErrors.
> Quad2dOpenGL 1285 Fix

- android/src/main/cpp/graphics/objects/Line2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorLineShaderOpenGl.cpp
- shared/src/map/layers/objects/Line2dLayerObject.cpp
> Line2dOpenGl

- shared/public/Tiled2dMapVectorLayer.h
- shared/public/VectorLayerDescription.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- shared/src/map/layers/tiled/vector/sublayers/polygon/Tiled2dMapVectorPolygonSubLayer.cpp
Add custom vector sublayer type and expose creator-function
> Custom Vector-Sublayer Type

- android/src/main/java/io/openmobilemaps/mapscore/map/scheduling/AndroidScheduler.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/scheduling/AndroidSchedulerDispatchers.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
Make AndroidScheduler and its dispatchers configurable, as well as tasks cancellable until they are run.
> AndroidScheduler Adjustments

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/Tiled2dMapZoomInfo.kt
- bridging/android/jni/map/layers/tiled/NativeTiled2dMapZoomInfo.cpp
- bridging/android/jni/map/layers/tiled/NativeTiled2dMapZoomInfo.h
- bridging/ios/MCTiled2dMapZoomInfo+Private.mm
- bridging/ios/MCTiled2dMapZoomInfo.h
- bridging/ios/MCTiled2dMapZoomInfo.mm
- shared/public/RasterVectorLayerDescription.h
- shared/public/Tiled2dMapSourceImpl.h
- shared/public/Tiled2dMapVectorLayerConfig.h
- shared/public/Tiled2dMapZoomInfo.h
- shared/src/map/layers/tiled/vector/sublayers/raster/Tiled2dMapVectorRasterSubLayerConfig.h
- shared/src/map/layers/tiled/wmts/WmtsCapabilitiesResource.cpp
Add option to set tiled layer under- and overzoom
> Under-/Overzoom

- shared/public/VectorTileGeometryHandler.h
- allow parsing of vector tiles in different coordinate systems
> Makes geometry handler more flexible

- shared/src/map/layers/objects/PolygonGroup2dLayerObject.cpp
- shared/src/map/layers/tiled/vector/sublayers/line/Tiled2dMapVectorLineSubLayer.cpp
- shared/src/map/layers/tiled/vector/sublayers/polygon/Tiled2dMapVectorPolygonSubLayer.cpp
Fix vector polygon sublayer for OpenGl, fixed crash when no selection delegate added to line/polygon sublayer
> OpenGl Polygon Sublayer

- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/text/TextLayer.cpp
Fixes problems when layers are added and removed fast.
> clears all addingQueues

- shared/public/Tiled2dMapLayerMaskWrapper.h
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- Struct zu Class für public/private
- Weniger calls zu Android/iOS
> refactor mask object to use safely for performance

- .github/workflows/sonatype-develop.yml
- .github/workflows/sonatype.yml
- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
Update to target 33 for Android, update AGP to 7.4.0, Kotlin to 1.8.0 and multiple other dependencies, add publishing to Ubique maven (repository of choice for dev builds).
> Publishing to Ubique Maven, AGP Update and target 33

- shared/public/CoordinatesUtil.h
> Include assert.h

- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
this still does not work along with generated masks
> Use mask that was set in raster layer

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.kt
- bridging/android/jni/map/layers/tiled/vector/NativeTiled2dMapVectorLayerInterface.cpp
- bridging/ios/MCTiled2dMapVectorLayerInterface+Private.mm
- bridging/ios/MCTiled2dMapVectorLayerInterface.h
- djinni/map/layers/tiled/raster/tiled_raster_layer.djinni
- djinni/map/layers/tiled/vector/tiled_vector_layer.djinni
- shared/public/Tiled2dMapVectorLayerInterface.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.cpp
- Konstruktor für Initialiasierung mit lokalem Style File
> adds layer initializer

- shared/public/PolygonHelper.h
- shared/src/map/layers/polygon/PolygonHelper.cpp
Add function to convert RectCoord to PolygonCoords in PolygonHelper
> PolygonCoords from RectCoord

- CHANGELOG.md
- android/gradle.properties
- android/readme.md
- android/src/main/java/io/openmobilemaps/mapscore/map/loader/DataLoader.kt
- android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt
- bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapInterface.kt
- bridging/android/jni/map/NativeMapInterface.cpp
- bridging/ios/MCMapInterface+Private.mm
- djinni/map/core.djinni
- ios/readme.md
- shared/public/MapInterface.h
- shared/src/MapsCoreSharedModule.cpp
- shared/src/map/MapScene.cpp
- Fix for Android context memory leak
> Release 1.5.2

- shared/src/map/layers/tiled/vector/Tiled2dMapVectorSource.cpp
Decode all vector data, if no specific layers requested
> Decode All 

- bridging/android/java/io/openmobilemaps/mapscore/shared/graphics/shader/TextShaderInterface.kt
- bridging/android/java/io/openmobilemaps/mapscore/shared/map/loader/FontWrapper.kt
- bridging/android/jni/graphics/shader/NativeTextShaderInterface.cpp
- bridging/android/jni/map/loader/NativeFontWrapper.cpp
- bridging/android/jni/map/loader/NativeFontWrapper.h
- bridging/ios/MCFontWrapper+Private.mm
- bridging/ios/MCFontWrapper.h
- bridging/ios/MCFontWrapper.mm
- bridging/ios/MCTextShaderInterface+Private.mm
- bridging/ios/MCTextShaderInterface.h
- djinni/graphics/shader/shader.djinni
- djinni/map/loader/loader.djinni
- ios/graphics/Shader/Metal/TextShader.metal
- ios/graphics/Shader/TextShader.swift
- ios/graphics/Texture/TextureHolder.swift
- ios/maps/MCFontLoader.swift
- shared/public/FontWrapper.h
- shared/public/SymbolVectorLayerDescription.h
- shared/public/TextHelper.h
- shared/public/TextLayerObject.h
- shared/public/TextShaderInterface.h
- shared/public/Tiled2dMapVectorLayerParserHelper.h
- shared/src/map/layers/text/TextHelper.cpp
- shared/src/map/layers/text/TextLayerObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSourceSymbolDataManager.cpp
- DP Algorithmus für Linienumbrüche
- Verbesserungen für Halo (implementiert halo_width)
> Implements line breaks and halo improvements

- android/src/main/cpp/graphics/shader/TextShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/TextShaderOpenGl.h
- android/src/main/java/io/openmobilemaps/mapscore/map/loader/FontLoader.kt
- Implementiert neue Text Shader
- Implementiert Font Loading (neue Texturen verwenden)
> OpenGL text improvements

- shared/src/map/layers/text/TextLayerObject.cpp
> Fixes line breaks

- android/build.gradle
Update publishing plugin for Android
> Update publishing plugin

- android/build.gradle
Downgrade to java 11 again (Issues with sealed classes)
> Downgrade to Java 11

- android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/PolygonPatternGroup2dOpenGl.cpp
- android/src/main/cpp/graphics/objects/PolygonPatternGroup2dOpenGl.h
- android/src/main/cpp/graphics/shader/BaseShaderProgramOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.h
- android/src/main/cpp/graphics/shader/PolygonPatternGroup2dShaderOpenGl.cpp
- android/src/main/cpp/graphics/shader/RasterShaderOpenGl.cpp
- shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonPatternTile.cpp
- shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonPatternTile.h
- shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonTile.h
Fixes polygon group stencil buffer function, fixes invalid sprite/uv coordinates case for pattern polygon, fixes polygon pattern in negative render coordinates space.
> Misc. OpenGL Polygon Fixes

- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceRasterTileDataManager.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceVectorTileDataManager.cpp
Fix crash when trying to update description for layers without subtiles available
> Update Layer Description Replace

- shared/src/map/camera/MapCamera2d.cpp
Fix moving to a coordinate of another reference system.
> Move to foreign coordinate

- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.h
Takes into account icon-anchor
> Handles icon-anchor

- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSourceSymbolDataManager.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.h
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.h
Return symbol coordinate as click coordinate for symbols in vector layers
> Symbol click coordinates

- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
Fix issue with chronological dependency of setup/update in vector layer symbol object
> Setup/Update Symbol RenderCoordinate

- shared/public/Tiled2dMapVectorTile.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceTileDataManager.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceTileDataManager.h
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSourceSymbolDataManager.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.h
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.h
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.h
- shared/src/map/layers/tiled/vector/tiles/line/Tiled2dMapVectorLineTile.cpp
- shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonTile.cpp
- shared/src/map/layers/tiled/vector/tiles/raster/Tiled2dMapVectorRasterTile.cpp
Properly propagate alpha value to existing and new vector layer subtiles and objects
> Vector layer alphas

- shared/src/map/layers/tiled/Tiled2dMapLayer.cpp
Add support for multiple sources for offscreen rendering.
> Offscreen Rendering Multiple Sources

- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceTileDataManager.cpp
Fix calls to clear of vector and raster layer tiles
> Clear Graphics Objects

- shared/public/Value.h
> implements single value asubtraction

- bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/vector/Tiled2dMapVectorLayerInterface.kt
- bridging/android/jni/map/layers/tiled/vector/NativeTiled2dMapVectorLayerInterface.cpp
- bridging/ios/MCTiled2dMapVectorLayerInterface+Private.mm
- djinni/map/layers/tiled/vector/tiled_vector_layer.djinni
- shared/public/TextLayer.h
- shared/public/Tiled2dMapVectorLayerInterface.h
- shared/src/map/MapScene.cpp
- shared/src/map/layers/icon/IconLayer.cpp
- shared/src/map/layers/icon/IconLayer.h
- shared/src/map/layers/line/LineLayer.cpp
- shared/src/map/layers/polygon/PolygonLayer.cpp
- shared/src/map/layers/text/TextLayer.cpp
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Cleaned up the functionality in onRemoved() and clear() for multiple layers to properly clear the graphics objects and the memory they used.
> Clean Up OnRemoved

- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.h
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.h
This reverts commit 7d2137579a0da0926670288bd8823423363186b9.
> Revert "performance improvements"

- ios/maps/MCTextureLoader.swift
Damit man den Cache in den DevTools löschen kann.
> expose URLCache, print errors for debugging

- shared/public/Tiled2dMapVectorStyleParser.h
- shared/public/Value.h
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorStyleParser.cpp
!has war noch nicht implementiert
> Implement !has Expression

- android/build.gradle
Update djinni, exclude android stl package, cleaner clean
> Android build.gradle adjustments, Djinni Update

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- shared/src/map/MapScene.cpp
- shared/src/map/scheduling/ThreadPoolSchedulerImpl.cpp
- shared/src/map/scheduling/ThreadPoolSchedulerImpl.h
> Scheduler pause/resume

- shared/public/Actor.h
- shared/src/map/layers/effect/SphereEffectLayer.cpp
- shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceDataManager.cpp
- shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceRasterTileDataManager.cpp
- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp
- improves weak actor logging
- use thread_local instead of static for local variables
- catch std::future exceptions
> fixes future exception

- jvm/src/main/java/io/openmobilemaps/mapscore/graphics/util/OSMesa.java
Initializing a BufferedImage via BufferedImage.setDataElement API is incredibly slow. Bypassing this and accessing the underlying data buffer directly makes a big difference.
> Optimize OSMesa Java bindings

- shared/src/map/coordinates/CoordinateConversionHelper.cpp
- Problem: To find a converter in the std::unordered_map is more expensive than single conversion (~factor 2)
- Keeps a shared_ptr of the last used converters s.t. this cached converter hits for all consecutively converted conversions from the same system
- thread_local cache, no need for mutexes
> Improves coordinate conversion by caching last converter

- shared/public/EarcutVectorView.h
- shared/public/VectorTileGeometryHandler.h
- Removes currentFeature vectors, directly fill coordinates-Vector
- Builds polygons as polygonRings with property isHole or not
- Adjusts EarcutVectorViews
> improves geometry parsing by less vector copying

- .github/workflows/benchmark.yml
- scripts/compare_benchmarks.py
This new workflow runs the benchmark on the PR and on the base branch compares the results and write them to the summary: https://github.com/openmobilemaps/maps-core/actions/runs/14063745811
> Adds compare benchmark script

- shared/src/map/layers/icon/IconLayer.cpp
Alpha is not set for the icons that were in the addingQueue.
> Fixes icon layer with alpha

- shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp
https://maplibre.org/maplibre-style-spec/sprite/
> Stretch sprite content field

- shared/src/map/camera/MapCamera3d.cpp
> Check pointers before accessing them in MapCamera3D

- shared/public/ValueVariant.h
- slightly faster, optimize for common case
- less code
> Optimizes value variant

- shared/public/Tiled2dMapTileInfo.h
- shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
Uses map that ignores t to find best matching t.
> Raster Best-T finding improvement
