CHANGELOG.md
ios/maps/MCMapView.swift
ios/maps/MCMapViewCallbackHandler.swift

This fixes a retain cycle in the iOS code which was introduced by `mapInterface.setCallbackHandler(self)`. This fixes Issue #56

fixes iOS retain cycle

---

android/consumer-rules.pro
android/src/main/java/io/openmobilemaps/mapscore/map/view/MapView.kt

Exclude reflection-dependant generated files from obfuscation/optimization, fixed a crash when registering an already started lifecycle

Android Proguard/Lifecycle Fix

---

shared/src/map/layers/icon/IconLayer.cpp
shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp

Added missing locking in the icon layer and ensure valid tile adjustments when pausing/resuming a raster tile layer.

Raster tile and icon layer fixes

---

android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp

Fix stencilOp for OpenGl quad rendering with masking optimization (single mask pre-render per pass).

Fix multi-layer quad rendering in single masked pass

---

android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp
shared/public/Tiled2dMapSourceImpl.h

Fix ColorGroup shaders for devices with limited clamp support, fix orientation of bounds for loaded tiles.

TileLoader bounds and GLSL clamp

---

shared/src/map/coordinates/CoordinateConversionHelper.cpp
shared/src/map/coordinates/CoordinateConversionHelper.h

Presaving the map coordinate to rendersystem, the std::map is used less in the innermost render loop.

Improves coordinate connversion helper performance

---

android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
shared/src/graphics/Renderer.cpp

Provide texture coords in OpenGl quad, even when no texture is loaded.

OpenGL Quad Texture Coordinates

---

shared/src/map/controls/DefaultTouchHandler.cpp

don't trigger DoubleClick after onClickUnconfirmed was handled

DoubleClick improvements

---

ios/graphics/Model/Quad2d.swift
ios/graphics/Model/Text/Text.swift
ios/graphics/RenderingContext.swift

this ignores the content of the stencil buffer

iOS: set stencil buffer to default mask if not masked

---

shared/src/map/MapScene.cpp
shared/src/map/camera/MapCamera2d.cpp

Don't call layer onRemoved() twice, fix crash in camera when removing non-existing listener.

OnRemove Fix / TouchListener Remove Fix

---

shared/src/map/MapScene.cpp

When adding a layer which is already added, remove it first to prevent duplicates

Adding Duplicate Layer

---

shared/public/AnimationInterpolator.h
shared/public/CoordAnimation.h
shared/public/DefaultAnimator.h
shared/src/map/camera/MapCamera2d.cpp
shared/src/map/camera/MapCamera2d.h

Compensate for padding change in ongoing camera animation, fix starting position for camera position animation (when padding is set)

Camera Animation With Padding 

---

shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp

this improves the flickering of transparent layers

Disable alpha animation if numDrawPreviousLayers == 0

---

shared/public/Tiled2dMapSourceImpl.h

due to rounding issues previously tiles that were not visible were loaded

Improves Tiled2dMapSourceImpl to only load really visible tiles

---

shared/src/map/camera/MapCamera2d.cpp

this fixes a race condition where the padding is set while a animation is running

Bugfix: Use end position value in coordinate animation

---

shared/src/map/MapScene.cpp

- test_and_set() setzt auf true und gibt letzten Wert zurück, war dieser bereits "true", so muss nichts gemacht werden, war er false müssen die Handler benachrichtigt werden
- vor dem Fix wurde nur ab 2x invalidate und dann immer benachrichtigt

Fixes invalidate

---

bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
bridging/android/jni/map/NativeMapCamera2dInterface.cpp
bridging/ios/MCMapCamera2dInterface+Private.mm
bridging/ios/MCMapCamera2dInterface.h
djinni/map/core.djinni
shared/public/MapCamera2dInterface.h
shared/src/map/camera/MapCamera2d.cpp
shared/src/map/camera/MapCamera2d.h

Use case: Veränderung der Bounds und dann Zurücksetzen auf die originalen Bounds. Für Offline Map, dass die Bounds für Selektion vergrössert werden, dann wieder zurück. Auch wohl sonst vielleicht mal sinnvoll.

Adds possibility to get bounds from camera

---

bridging/android/java/io/openmobilemaps/mapscore/shared/map/MapCamera2dInterface.kt
bridging/android/java/io/openmobilemaps/mapscore/shared/map/layers/tiled/Tiled2dMapZoomInfo.kt
bridging/android/jni/map/NativeMapCamera2dInterface.cpp
bridging/android/jni/map/layers/tiled/NativeTiled2dMapZoomInfo.cpp
bridging/android/jni/map/layers/tiled/NativeTiled2dMapZoomInfo.h
bridging/ios/MCMapCamera2dInterface+Private.mm
bridging/ios/MCMapCamera2dInterface.h
bridging/ios/MCTiled2dMapZoomInfo+Private.mm
bridging/ios/MCTiled2dMapZoomInfo.h
bridging/ios/MCTiled2dMapZoomInfo.mm
djinni/map/core.djinni
djinni/map/layers/tiled/tiled_layer.djinni
shared/public/MapCamera2dInterface.h
shared/public/Tiled2dMapSource.h
shared/public/Tiled2dMapSourceImpl.h
shared/public/Tiled2dMapZoomInfo.h
shared/src/map/camera/MapCamera2d.cpp
shared/src/map/camera/MapCamera2d.h
shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
shared/src/map/layers/tiled/raster/Tiled2dMapRasterSource.cpp
shared/src/map/layers/tiled/raster/Tiled2dMapRasterSource.h
shared/src/map/layers/tiled/wmts/WmtsCapabilitiesResource.cpp

The WMTS Scale Denominator is defined with respect to a standardized rendering pixel of [0.28mm x 0.28mm.](https://gis.stackexchange.com/questions/315881/what-is-wmts-scaledenominator) Therefore when placing tiled layer this has to be taken into account.
What does this change:
Currently a Tiled2dMapRasterLayer was always rendered in the same size as if it was displayed on a ~90 ppi display. This almost always results in a blurry image since [all mobile devices](https://screensiz.es) have a much higher ppi.
Users of the SDK potentially have to change their zoomLevelScaleFactor to adapt to this change.
This can be enabled by setting the adaptScaleToScreen flag to true. Since this flag has to be set this is a breaking change to the API and users of the SDK have to explicitly set it and …

Calculate tiled layer scale in Tiled2dMapSourceImpl

---

android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
shared/public/Tiled2dMapSource.h
shared/public/Tiled2dMapSourceImpl.h
shared/src/map/MapScene.cpp
shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp
shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.h

Fixed ready-query for textured OpenGL Quad, fixed order of Tiled2dMapRasterLayer updates and reduce unnessecary parallel tile source updates

Tile Updates

---

ios/graphics/Model/Line/LineGroup2d.swift

Maske setzt erlaubte Region auf 1000_0000, Linie nimmt Referenz 0000_0001, falls kleiner darf gezeichnet werden (.less), danach darf dort nicht mehr gezeichnet werden, also auf .zero, dass 0000_0001 immer grösser.

fixes masked line groups

---

shared/src/map/camera/MapCamera2d.cpp

Padding was shared on both sides equally, now the correct padding is applied (even for right-to-left (bottom-to-top) systems).

Fixes getPaddingCorrectedBounds

---

ios/graphics/Texture/TextureHolder.swift
ios/maps/MCTextureLoader.swift

Now the behavior is the same as on android.
Crash Stacktrace:
```
Crashed: com.apple.mtktextureloaderload
0  MetalKit                       0xd68c +[MTKTextureLoaderKTX isKTXFile:] + 28
1  MetalKit                       0x9fcc -[MTKTextureLoader _determineFileType:] + 40
2  MetalKit                       0xa380 -[MTKTextureLoader _loadData:options:uploader:label:completionHandler:] + 72
3  MetalKit                       0xa0d0 -[MTKTextureLoader _loadData:options:completionHandler:] + 164
4  MetalKit                       0x94a8 __65-[MTKTextureLoader newTextureWithData:options:completionHandler:]_block_invoke + 56
5  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
7  libdispatch.dylib …
```

fixes metal crash when attempting to load empty texture

---

shared/public/Tiled2dMapSourceImpl.h

- [remove tiles that are not needed anymore from loading Queue](https://github.com/openmobilemaps/maps-core/commit/12e348a0f078314b23c76439b9e1aca800f98d7d)
- [update priority for tiles already in loading queue](https://github.com/openmobilemaps/maps-core/commit/7ca328dac8b7ec638142094c2ba792be6757bc2a)

Bugfix: tile loading

---

android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
android/src/main/cpp/graphics/objects/Quad2dOpenGl.h

Fix Quad2dOpenGl when using texture coords without a texture.

Quad2dOpenGl TextureCoords Only

---

shared/public/Tiled2dMapVectorLayer.h
shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp

Expose multiple Tiled2dMapVectorLayer functions for subclasses, enable override of layer config creation

Tiled2dMapVectorLayer Functions

---

shared/public/Tiled2dMapVectorLayer.h
shared/public/VectorMapDescription.h
shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp

Make sprites in VectorLayer optional, allow for more complex layer constructors in subclasses.

VectorLayer Subclass Adjustments

---

ios/graphics/Model/Polygon/Polygon2d.swift

Masks setzen die oberen 2 Bits, muss so gecheckt werden.

fixes masking in polygon2d

---

.github/workflows/android.yml

Limit pull-request Android build checks to single abi type (arm64-v8a)

Simplify Android PR Builds

---

ios/graphics/Helpers/OSLock.swift
ios/graphics/Model/BaseGraphicsObject.swift
ios/graphics/Model/Line/LineGroup2d.swift
ios/graphics/Model/Polygon/Polygon2d.swift
ios/graphics/Model/Polygon/PolygonGroup2d.swift
ios/graphics/Model/Quad2d.swift
ios/graphics/Model/Text/Text.swift

Currently a race condition can happen if the properties of a graphics object are updated while the object is being rendered.
If an object is updated very frequently there is a good chance this happens. Therefore I introduced the concept of locking in iOS graphics objects.
The locking mechanism used is [os_unfair_lock](https://developer.apple.com/documentation/os/1646466-os_unfair_lock_lock) since it is the faster mechanism on iOS according to: https://serhiybutz.medium.com/swift-mutex-benchmark-b21ee293d9ad

iOS: Graphics object race conditions

---

shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp

Propagate the touch events in the vector layer in reverse order (as visible)

Reverse Touch Propagation in VectorLayer

---

shared/public/Tiled2dMapSourceImpl.h
shared/src/map/layers/tiled/raster/Tiled2dMapRasterLayer.cpp

- Verbessert Ladegeschwindigkeit durch bessere Score für Priority (Layer nahe bei gleichem z wie aktuell gerendert werden früher geladen)
- Ausnutzen von Optimierung mit vorgespeicherten GraphicsObject Pointern verbessert Performance
- Masking: berechnet Maske für alle Tiles, auch nicht ready

improves loading performance and masking

---

Package.swift

Availability ist zu strikt eingestellt, da es auch auf iOS 12.0 funktionieren sollte, man es aber zur Buildzeit noch nicht weiss.

updates package to fix xcode 14.3.0 problems

---

shared/src/map/layers/tiled/vector/Tiled2dMapVectorSource.cpp

Load for all vector layer configs, when no layers to decode are specified

Load for all vector layer configs

---

shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceTileDataManager.cpp
shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSourceSymbolDataManager.cpp

Correctly schedule the setup of the sprite data in existing subtiles on the graphics thread

Sprite data in existing subtiles

---

shared/public/LineVectorLayerDescription.h
shared/public/PolygonVectorLayerDescription.h
shared/public/RasterVectorLayerDescription.h
shared/public/SymbolVectorLayerDescription.h
shared/public/Tiled2dMapVectorLayerConfig.h
shared/public/Tiled2dMapVectorLayerParserHelper.h
shared/public/VectorLayerDescription.h
shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
shared/src/map/layers/tiled/vector/Tiled2dMapVectorRasterSubLayerConfig.h
shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceRasterTileDataManager.cpp
shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceVectorTileDataManager.cpp
shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSourceSymbolDataManager.cpp
shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonPatternTile.cpp
shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonTile.cpp

Rename sourceId to sourceLayer (consistent with style specs), use source name for VectorLayer raster sublayer identification.

Vector raster sub-layer identification

---

shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp

When inserting a vector layer from a style.json and setting the alpha immediately afterwards, this change has no effect because the source manager is initialized after the call to `setAlpha` and does not set the alpha during initialization like for a raster layer.

Set alpha when initializing non-raster vector layer

---

shared/src/map/scheduling/ThreadPoolSchedulerImpl.cpp
shared/src/map/scheduling/ThreadPoolSchedulerImpl.h

otherwise it is easy to run into a deadlock with devices with 2 concurrent threads

make sure that at least 8 threads are created

---

shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp

Swisstopo kombiniert in einem Layer Stretch-Icons und rotirte Icons.
Damit das funktioniert, wird mit diesem Change die Rotation auch in `updateStretchIconProperties` gesetzt.
`{
"id": "stop_location_rotation_flat",
"type": "symbol",
"source": "78a2de85-ca3c-4b41-b9a3-1ced5da8bcf0",
"source-layer": "poi",
"minzoom": 14,
"maxzoom": 22,
"layout": {
"icon-size": ["interpolate", ["linear"], ["zoom"], 13, 0.2, 18, 0.4],
"text-font": ["Frutiger Neue Condensed Regular"],
"icon-image": [
"case",
["has", "direction"],
"blue_round_arrow",
"blue_round_white_dot"
],
"visibility": "visible",
"icon-rotate": ["to-number", ["get", "direction"]],
"icon-text-fit": "width",
"symbol-placement": "point",
"icon-allow-overlap": true,
"text-allow-overlap": true,
"icon-pitch-alignment": "map", …

Allow Rotation for Stretch Icons

---

shared/public/TextHelper.h
shared/public/Tiled2dMapVectorLayer.h
shared/src/map/layers/text/TextHelper.cpp

Summiert die Newline cost nicht mehr, weniger line breaks bei line breaks. Wendet \n immer zwingend an.

fixes problem with new lines

---

shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp

this fixes a random crash when generating the renderpasses

Lock the mailbox of the vector layer actor after creating it

---

shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayerParserHelper.cpp

This pull request includes changes to the `Tiled2dMapVectorLayerParserHelper` class to update the maximum zoom level and adjust the zoom level parameters in various parts of the code.
Changes to zoom levels:
* [`shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayerParserHelper.cpp`](diffhunk://#diff-b5b2f7b1f4f4acf3c840bab111d316349bffef79fe1fdf0a395ab10b670ff348L107-R107): Updated the maximum zoom level from 22 to 24 in multiple instances within the `parseStyleJ` method. [[1]](diffhunk://#diff-b5b2f7b1f4f4acf3c840bab111d316349bffef79fe1fdf0a395ab10b670ff348L107-R107) [[2]](diffhunk://#diff-b5b2f7b1f4f4acf3c840bab111d316349bffef79fe1fdf0a395ab10b670ff348L169-R177) [[3]](diffhunk://#diff-b5b2f7b1f4f4acf3c840bab111d316349bffef79fe1fdf0a395ab10b670ff348L267-R267)
Adjustments to zoom level …

improve zoom level limit parsing

---

shared/public/Tiled2dMapSource.h
shared/public/Tiled2dMapSourceImpl.h

TileWrapper keeps a gpc_polygon which is not freed on destruction of the TileWrapper. In some cases this was explicitly freed, but not everywhere. To simplify this, wrap the gpc_polygon in a semi-safe holder to ensure its always destroyed.
Unfortunately the gpc_... API does not use const pointers for the input arguments, so the wrapper cannot be made properly safe.
Also, add missing intitialization for Tiled2dMapSource::curT/curZoom, reported by valgrind.

Fix memory leak from gpc_polygon in TileWrapper

---

jvm/src/main/java/io/openmobilemaps/mapscore/map/loader/BaseDataLoader.java
jvm/src/test/java/io/openmobilemaps/mapscore/BaseDataLoaderTest.java

In the BaseDataLoader::loadData/TextureAsync, a child class can return a future that may already be completed (or failed) at the time that it is being created. For such a future, the whenComplete callback is called immediately from the same callstack.
During creating an entry for the ongoing load via
ConcurrentHashMap::compute, this whenComplete callback would then try to remove that same entry. This is both nonsensical and illegal. Use whenCompleteAsync to ensure that this is deferred until after the entry has been created.

Java bindings: handle BaseDataLoader immediately resolved futures

---

.github/workflows/test.yml
shared/test/CMakeLists.txt
shared/test/TestGeoJsonParser.cpp
shared/test/TestGeometryHandler.cpp
shared/test/TestSymbolAnimationCoordinatorMap.cpp
shared/test/helper/TestData.cpp
shared/test/helper/TestData.h

Determine the absolute path to the test data directory at build time.
This allows to run the test binary from any working directory.
If necessary, the data directory can be overridden at runtime via the
environment variable OPENMOBILEMAPS_TESTDATA_DIR.
Tangent: in TestGeometryHandler benchmarks, move reading of file data out of measured block.
And, also in TestGeometryHandler, initialize a CoordinateConversionHandler directly with a render system instead of (ab-)using the "independent instance" -- the internal renderSystemConverter is otherwise not properly set.

Load test data independent of working directory 

---

shared/public/Tiled2dMapVectorStateManager.h
shared/public/Value.h
shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolGroup.cpp

Creating the symbols objects is expensive.
If the symbols won't ever show up because they never have an icon nor a text label, this is wasted effort. Many styles seem explicitly filter symbols like this explicitly, but this is easy to miss.
For this, (re-)introduce a zoom-independent EvaluationContext, allowing to potentially evaluate a value without zoom.

Filter symbols with neither text nor icon early

---

shared/src/map/layers/tiled/vector/tiles/line/Tiled2dMapVectorLineTile.cpp

PerformClick coordinate argument is in mapCoordinateSystem and not always EPSG3857. The conversion to render coordinates then is most of the time garbage and not correctly comparable to the correctly converted render coordinates.

Use correct coordinate system identifier for line click

---

android/src/main/cpp/graphics/objects/GraphicsObjectFactoryOpenGl.cpp
android/src/main/cpp/graphics/objects/GraphicsObjectFactoryOpenGl.h
android/src/main/cpp/graphics/objects/IcosahedronOpenGl.cpp
android/src/main/cpp/graphics/objects/IcosahedronOpenGl.h
android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.cpp
android/src/main/cpp/graphics/objects/LineGroup2dOpenGl.h
android/src/main/cpp/graphics/objects/Polygon2dOpenGl.cpp
android/src/main/cpp/graphics/objects/Polygon2dOpenGl.h
android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.cpp
android/src/main/cpp/graphics/objects/PolygonGroup2dOpenGl.h
android/src/main/cpp/graphics/objects/PolygonPatternGroup2dOpenGl.cpp
android/src/main/cpp/graphics/objects/PolygonPatternGroup2dOpenGl.h
android/src/main/cpp/graphics/objects/Quad2dInstancedOpenGl.cpp
android/src/main/cpp/graphics/objects/Quad2dInstancedOpenGl.h
android/src/main/cpp/graphics/objects/Quad2dOpenGl.cpp
android/src/main/cpp/graphics/objects/Quad2dOpenGl.h
android/src/main/cpp/graphics/objects/Quad2dStretchedInstancedOpenGl.cpp
android/src/main/cpp/graphics/objects/Quad2dStretchedInstancedOpenGl.h
android/src/main/cpp/graphics/objects/Text2dInstancedOpenGl.cpp
android/src/main/cpp/graphics/objects/Text2dInstancedOpenGl.h
android/src/main/cpp/graphics/objects/Text2dOpenGl.cpp
android/src/main/cpp/graphics/objects/Text2dOpenGl.h
android/src/main/cpp/graphics/shader/BaseShaderProgramOpenGl.h
android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.h
android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp
android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.h
shared/src/map/layers/tiled/vector/sourcemanagers/Tiled2dMapVectorSourceVectorTileDataManager.cpp

Introducing UBOs for OpenGL line/polygon groups has led to potentially uninitialized states in these buffers. To prevent shaders from rendering in such situations or when the buffers are in an unusable state, the GL graphics objects now query the shader's state. This allows for skipping the drawing of objects at the earliest possible moment, avoiding the need for the vertex or fragment shader to handle fundamentally invalid states and preventing unnecessary partial executions of the pipeline.

GlShaders Renderability

---

ios/graphics/Pipelines/RenderToImageRenderPass.swift

- Prevents Crashes on Simulator where Shared Stencil buffers are not possible
- Changing a stencil buffer from Shared to Private moves its memory from being accessible by both CPU and GPU to being optimized solely for the GPU, making rendering faster but preventing direct CPU access. Direct CPU access is not needed for "toImageRendering", so this is not needed anyway.

Uses private storage mode for stencil buffer

---

CMakeLists.txt
jvm/CMakeLists.txt

With the changes to djinni, we no longer need to set DATAREF_XXX macros, allowing to build support-lib/cpp directly into the mapscore core library. This simplifies/allows using DataRef in tests, without requiring language bindings. See https://github.com/UbiqueInnovation/djinni/pull/24.

Update to djinni 1.1.0

---

android/src/main/cpp/graphics/shader/ColorLineGroup2dShaderOpenGl.cpp
android/src/main/cpp/graphics/shader/ColorPolygonGroup2dShaderOpenGl.cpp

- layout(binding = 0) is not supported, use glUniformBlockBinding instead
- Uniform block data may require padding after last toplevel block entry. This seems to always be the case with std140 layout. WebGL enforces this strictly. Technically, providing a too small buffer is undefined behaviour.
- Explicitly set precision qualifier for numStyles. Otherwise, vertex and fragment shader default to incompatible precision settings in WebGL, and the program fails to link.

Make Uniform Buffer Object handling compatible with WebGL

---

shared/public/Tiled2dMapRasterSource.h
shared/public/Tiled2dMapSource.h
shared/public/Tiled2dMapSourceImpl.h
shared/public/Tiled2dMapVectorSource.h
shared/public/VectorSet.h
shared/src/map/layers/tiled/raster/Tiled2dMapRasterSource.cpp
shared/src/map/layers/tiled/vector/Tiled2dMapVectorLayer.cpp
shared/src/map/layers/tiled/vector/Tiled2dMapVectorSource.cpp
shared/src/map/layers/tiled/vector/geojson/Tiled2dVectorGeoJsonSource.h
shared/test/TestTileSource.cpp
shared/test/helper/TestScheduler.h

In 5d95aef, a limit to the number of concurrent tile loads was introduced. As a fallback to the next loader in the loader cascade was performed immediately, slow "fallback" loaders could block the subsequent tile loads from the "primary" loaders.
In the somewhat common loader cascade setup to load from offline data first and then fallback to a remote request, blocking the local loads with a slow remote loader can be disastrous.
For now, we keep the same fixed number of concurrent load "slots" and strictly prioritize by loader index. That is, all loads for loader 0 are processed before the loads for loader 1, etc.
Alternatively, the slots could be divided in any scheme among the loaders, as long as the primary loader is never starved.
The Tiled2dMapSource now has to explicitly handle a NOP …

MAP-54: Prioritize data loads per loader, so fallback cannot block primary

---

CHANGELOG.md
android/gradle.properties
android/readme.md
android/src/main/java/io/openmobilemaps/mapscore/map/util/MapRenderHelper.kt
ios/readme.md
shared/src/MapsCoreSharedModule.cpp
shared/src/map/MapScene.cpp

Including fix: 
- Properly lock layer access in drawReadyFrame, cooperatively cancel offscreen rendering with inactive coroutine context on Android.

Release 3.1.3

---

shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolObject.cpp

- Icon-Offset should be modified by `iconSize` (scale property), not actual "icon size"
- Direction of offset should be rotated

MAP-57: Fix Icon Offset

---

ios/maps/MCMapView.swift

If MCMapView is deallocated before all three GPU buffers have finished, the following assertion is triggered:
`BUG IN CLIENT OF LIBDISPATCH: Semaphore object deallocated while in use (current value < original value)`
This causes the app to crash.
Unfortunately, the only solution I found is to signal the buffer count in the deinit as proposed here: https://developer.apple.com/forums/thread/126781

"fixes" semaphore that can happen on dealloc of mapView

---

ios/graphics/Shader/Metal/LineShader.metal

Use float as we do for normal line fragment shader.

fixes iOS precision issue for simple line

---

shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp

- [use unrotated box for dimension calculation](https://github.com/openmobilemaps/maps-core/commit/9c4862d35e0c513b801e72ffcac9fec32b9db9f2)

Bugfix: rotated stretch icon

---

ios/graphics/Shader/Metal/TextInstancedShader.metal

optimize rendering by moving hidden labels offscreen to skip unnecessary fragment shading

---

ios/graphics/RenderingContext.swift
ios/graphics/Shader/BaseShader.swift

- Hash and !== are the same for MTLPipelineRenderState
- setupProgram is done before rendering anyway, if object does not come to this phase, it is done for nothing...

Performance improvements

---

shared/src/map/layers/icon/IconLayer.cpp

Fixed a mismatch between an icon touch area and its displayed image.
[Related issue](https://github.com/geoadmin/lib-open-swiss-maps-sdk/issues/185)

Fixed icon touch area check

---

shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp
shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.h

- Reference Point Indices only change in 3d
- Calculate indices only once and on reversal in 2d
- In 3d still in any case in the update

removes findReferencePointIndices in every update in 2d

---

shared/public/Value.h
shared/src/map/layers/tiled/vector/tiles/line/Tiled2dMapVectorLineTile.cpp
shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonPatternTile.cpp
shared/src/map/layers/tiled/vector/tiles/polygon/Tiled2dMapVectorPolygonTile.cpp

For polygon, line, polygon pattern the filter is potentially used across a big number of features, however often the identifiers are the same for these geometries.
It's better to cache them then to reevaluate every time.

Adds filter caching

---

.github/workflows/jvm_build.yml
.github/workflows/jvm_package_deploy.yml

Release builds were failing because they were running on the older ubuntu github runners. This was different to the runners that was running the test build, which meant that some build problems (with older C++ library) only showed up during release build.
The reason to use the older runners was to ensure that we link against the ubuntu-22.04 glibc. This is no longer needed for our internal builds.
Also, expand the jvm_build job instead of using the workflow template (to set runs-on). This makes it easy to enable ccache.

github: fix JVM release builds, use same runner for jvm_build and jvm_package_deploy

---

shared/src/map/layers/tiled/vector/symbol/Tiled2dMapVectorSymbolLabelObject.cpp

Median computation on the last line does a out-of-bounds access in the heights array if the last line is a newline-character.
Fixed by setting the medianLastBaseLine on the full line height if the line is empty.

Fixes crash on trailing new lines

---

shared/src/map/camera/MapCamera3d.cpp

Only cancel zoom/coordinate animations when starting new animations on setting the camera 3d config

Camera 3d Config Animation Cancellation

---

ios/graphics/Model/Line/LineGroup2d.swift
ios/graphics/Model/Polygon/PolygonGroup2d.swift
ios/graphics/Model/Polygon/PolygonPatternGroup2d.swift

Fix stencil reference value for unmasked objects in masked render passes

iOS isPassMasked stencil fixes
